// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha1 "k8s.io/api/computeresources/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	computeresources "k8s.io/kubernetes/pkg/apis/computeresources"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ResourceClass_To_computeresources_ResourceClass,
		Convert_computeresources_ResourceClass_To_v1alpha1_ResourceClass,
		Convert_v1alpha1_ResourceClassList_To_computeresources_ResourceClassList,
		Convert_computeresources_ResourceClassList_To_v1alpha1_ResourceClassList,
		Convert_v1alpha1_ResourceClassSpec_To_computeresources_ResourceClassSpec,
		Convert_computeresources_ResourceClassSpec_To_v1alpha1_ResourceClassSpec,
		Convert_v1alpha1_ResourceClassStatus_To_computeresources_ResourceClassStatus,
		Convert_computeresources_ResourceClassStatus_To_v1alpha1_ResourceClassStatus,
		Convert_v1alpha1_ResourcePropertySelector_To_computeresources_ResourcePropertySelector,
		Convert_computeresources_ResourcePropertySelector_To_v1alpha1_ResourcePropertySelector,
		Convert_v1alpha1_ResourceSelectorRequirement_To_computeresources_ResourceSelectorRequirement,
		Convert_computeresources_ResourceSelectorRequirement_To_v1alpha1_ResourceSelectorRequirement,
	)
}

func autoConvert_v1alpha1_ResourceClass_To_computeresources_ResourceClass(in *v1alpha1.ResourceClass, out *computeresources.ResourceClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ResourceClassSpec_To_computeresources_ResourceClassSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ResourceClassStatus_To_computeresources_ResourceClassStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ResourceClass_To_computeresources_ResourceClass is an autogenerated conversion function.
func Convert_v1alpha1_ResourceClass_To_computeresources_ResourceClass(in *v1alpha1.ResourceClass, out *computeresources.ResourceClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceClass_To_computeresources_ResourceClass(in, out, s)
}

func autoConvert_computeresources_ResourceClass_To_v1alpha1_ResourceClass(in *computeresources.ResourceClass, out *v1alpha1.ResourceClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_computeresources_ResourceClassSpec_To_v1alpha1_ResourceClassSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_computeresources_ResourceClassStatus_To_v1alpha1_ResourceClassStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_computeresources_ResourceClass_To_v1alpha1_ResourceClass is an autogenerated conversion function.
func Convert_computeresources_ResourceClass_To_v1alpha1_ResourceClass(in *computeresources.ResourceClass, out *v1alpha1.ResourceClass, s conversion.Scope) error {
	return autoConvert_computeresources_ResourceClass_To_v1alpha1_ResourceClass(in, out, s)
}

func autoConvert_v1alpha1_ResourceClassList_To_computeresources_ResourceClassList(in *v1alpha1.ResourceClassList, out *computeresources.ResourceClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]computeresources.ResourceClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ResourceClassList_To_computeresources_ResourceClassList is an autogenerated conversion function.
func Convert_v1alpha1_ResourceClassList_To_computeresources_ResourceClassList(in *v1alpha1.ResourceClassList, out *computeresources.ResourceClassList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceClassList_To_computeresources_ResourceClassList(in, out, s)
}

func autoConvert_computeresources_ResourceClassList_To_v1alpha1_ResourceClassList(in *computeresources.ResourceClassList, out *v1alpha1.ResourceClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.ResourceClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_computeresources_ResourceClassList_To_v1alpha1_ResourceClassList is an autogenerated conversion function.
func Convert_computeresources_ResourceClassList_To_v1alpha1_ResourceClassList(in *computeresources.ResourceClassList, out *v1alpha1.ResourceClassList, s conversion.Scope) error {
	return autoConvert_computeresources_ResourceClassList_To_v1alpha1_ResourceClassList(in, out, s)
}

func autoConvert_v1alpha1_ResourceClassSpec_To_computeresources_ResourceClassSpec(in *v1alpha1.ResourceClassSpec, out *computeresources.ResourceClassSpec, s conversion.Scope) error {
	out.ResourceSelector = *(*[]computeresources.ResourcePropertySelector)(unsafe.Pointer(&in.ResourceSelector))
	out.Priority = in.Priority
	return nil
}

// Convert_v1alpha1_ResourceClassSpec_To_computeresources_ResourceClassSpec is an autogenerated conversion function.
func Convert_v1alpha1_ResourceClassSpec_To_computeresources_ResourceClassSpec(in *v1alpha1.ResourceClassSpec, out *computeresources.ResourceClassSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceClassSpec_To_computeresources_ResourceClassSpec(in, out, s)
}

func autoConvert_computeresources_ResourceClassSpec_To_v1alpha1_ResourceClassSpec(in *computeresources.ResourceClassSpec, out *v1alpha1.ResourceClassSpec, s conversion.Scope) error {
	out.ResourceSelector = *(*[]v1alpha1.ResourcePropertySelector)(unsafe.Pointer(&in.ResourceSelector))
	out.Priority = in.Priority
	return nil
}

// Convert_computeresources_ResourceClassSpec_To_v1alpha1_ResourceClassSpec is an autogenerated conversion function.
func Convert_computeresources_ResourceClassSpec_To_v1alpha1_ResourceClassSpec(in *computeresources.ResourceClassSpec, out *v1alpha1.ResourceClassSpec, s conversion.Scope) error {
	return autoConvert_computeresources_ResourceClassSpec_To_v1alpha1_ResourceClassSpec(in, out, s)
}

func autoConvert_v1alpha1_ResourceClassStatus_To_computeresources_ResourceClassStatus(in *v1alpha1.ResourceClassStatus, out *computeresources.ResourceClassStatus, s conversion.Scope) error {
	out.Allocatable = in.Allocatable
	out.Request = in.Request
	return nil
}

// Convert_v1alpha1_ResourceClassStatus_To_computeresources_ResourceClassStatus is an autogenerated conversion function.
func Convert_v1alpha1_ResourceClassStatus_To_computeresources_ResourceClassStatus(in *v1alpha1.ResourceClassStatus, out *computeresources.ResourceClassStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceClassStatus_To_computeresources_ResourceClassStatus(in, out, s)
}

func autoConvert_computeresources_ResourceClassStatus_To_v1alpha1_ResourceClassStatus(in *computeresources.ResourceClassStatus, out *v1alpha1.ResourceClassStatus, s conversion.Scope) error {
	out.Allocatable = in.Allocatable
	out.Request = in.Request
	return nil
}

// Convert_computeresources_ResourceClassStatus_To_v1alpha1_ResourceClassStatus is an autogenerated conversion function.
func Convert_computeresources_ResourceClassStatus_To_v1alpha1_ResourceClassStatus(in *computeresources.ResourceClassStatus, out *v1alpha1.ResourceClassStatus, s conversion.Scope) error {
	return autoConvert_computeresources_ResourceClassStatus_To_v1alpha1_ResourceClassStatus(in, out, s)
}

func autoConvert_v1alpha1_ResourcePropertySelector_To_computeresources_ResourcePropertySelector(in *v1alpha1.ResourcePropertySelector, out *computeresources.ResourcePropertySelector, s conversion.Scope) error {
	out.MatchExpressions = *(*[]computeresources.ResourceSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_v1alpha1_ResourcePropertySelector_To_computeresources_ResourcePropertySelector is an autogenerated conversion function.
func Convert_v1alpha1_ResourcePropertySelector_To_computeresources_ResourcePropertySelector(in *v1alpha1.ResourcePropertySelector, out *computeresources.ResourcePropertySelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourcePropertySelector_To_computeresources_ResourcePropertySelector(in, out, s)
}

func autoConvert_computeresources_ResourcePropertySelector_To_v1alpha1_ResourcePropertySelector(in *computeresources.ResourcePropertySelector, out *v1alpha1.ResourcePropertySelector, s conversion.Scope) error {
	out.MatchExpressions = *(*[]v1alpha1.ResourceSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_computeresources_ResourcePropertySelector_To_v1alpha1_ResourcePropertySelector is an autogenerated conversion function.
func Convert_computeresources_ResourcePropertySelector_To_v1alpha1_ResourcePropertySelector(in *computeresources.ResourcePropertySelector, out *v1alpha1.ResourcePropertySelector, s conversion.Scope) error {
	return autoConvert_computeresources_ResourcePropertySelector_To_v1alpha1_ResourcePropertySelector(in, out, s)
}

func autoConvert_v1alpha1_ResourceSelectorRequirement_To_computeresources_ResourceSelectorRequirement(in *v1alpha1.ResourceSelectorRequirement, out *computeresources.ResourceSelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	out.Operator = computeresources.ResourceSelectorOperator(in.Operator)
	return nil
}

// Convert_v1alpha1_ResourceSelectorRequirement_To_computeresources_ResourceSelectorRequirement is an autogenerated conversion function.
func Convert_v1alpha1_ResourceSelectorRequirement_To_computeresources_ResourceSelectorRequirement(in *v1alpha1.ResourceSelectorRequirement, out *computeresources.ResourceSelectorRequirement, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceSelectorRequirement_To_computeresources_ResourceSelectorRequirement(in, out, s)
}

func autoConvert_computeresources_ResourceSelectorRequirement_To_v1alpha1_ResourceSelectorRequirement(in *computeresources.ResourceSelectorRequirement, out *v1alpha1.ResourceSelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	out.Operator = v1alpha1.ResourceSelectorOperator(in.Operator)
	return nil
}

// Convert_computeresources_ResourceSelectorRequirement_To_v1alpha1_ResourceSelectorRequirement is an autogenerated conversion function.
func Convert_computeresources_ResourceSelectorRequirement_To_v1alpha1_ResourceSelectorRequirement(in *computeresources.ResourceSelectorRequirement, out *v1alpha1.ResourceSelectorRequirement, s conversion.Scope) error {
	return autoConvert_computeresources_ResourceSelectorRequirement_To_v1alpha1_ResourceSelectorRequirement(in, out, s)
}
