/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

import (
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	api "k8s.io/kubernetes/pkg/api"
)

// ResourceClassLister helps list ResourceClasses.
type ResourceClassLister interface {
	// List lists all ResourceClasses in the indexer.
	List(selector labels.Selector) (ret []*api.ResourceClass, err error)
	// Get retrieves the ResourceClass from the index for a given name.
	Get(name string) (*api.ResourceClass, error)
	ResourceClassListerExpansion
}

// resourceClassLister implements the ResourceClassLister interface.
type resourceClassLister struct {
	indexer cache.Indexer
}

// NewResourceClassLister returns a new ResourceClassLister.
func NewResourceClassLister(indexer cache.Indexer) ResourceClassLister {
	return &resourceClassLister{indexer: indexer}
}

// List lists all ResourceClasses in the indexer.
func (s *resourceClassLister) List(selector labels.Selector) (ret []*api.ResourceClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*api.ResourceClass))
	})
	return ret, err
}

// Get retrieves the ResourceClass from the index for a given name.
func (s *resourceClassLister) Get(name string) (*api.ResourceClass, error) {
	key := &api.ResourceClass{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(api.Resource("resourceclass"), name)
	}
	return obj.(*api.ResourceClass), nil
}
